name: "colehawk-mtl-t5-v11-base"
node_type: "p4d.24xlarge"
node_num: 8
image: "747303060528.dkr.ecr.us-east-2.amazonaws.com/mstar-eks:adirawal-mtl_aug22"
command: ["/bin/bash"]
args: [
 "scripts/t50_launch.sh",
 "cole_aug22_t5_v11_base",
 "96",
 "0",
 "1",
 "100000",
 "google/t5-v1_1-base",
 "512",
]
