args:
- pretrain_main.py
- run_name=11B_t5_prod_candidate
- trainer.max_steps=2000000
- optimizer.base_learning_rate=0.0001
- trainer.num_nodes=64
- optimizer.micro_batch_size=2
- optimizer.total_batch_size=1024
- data=t5_prod_drop_2
- model=11B
- model.positional_embedding=alibi
- deepspeed_path=config/deepspeed/bf16_zero2d.json
- trainer.precision=bf16 
- trainer.num_sanity_val_steps=0
- trainer.limit_val_batches=50
- model.ckpt_path=/mnt_out/colehawk/easel/11B_t5_prod_candidate/09_25_03_52/epoch\=0-step\=120000-validation_loss\=1.1115_training_loss_step\=1.1011.ckpt/
command:
- /usr/bin/python3
image: 747303060528.dkr.ecr.us-east-1.amazonaws.com/mstar-eks:colehawk-bedrock
name: chawk-bdrk-t5-11B
node_num: 64
node_type: p4d.24xlarge
