args:
- pretrain_main.py
- run_name=20B_t5_prod_candidate
- trainer.max_steps=2000000
- optimizer.base_learning_rate=0.0001
- data=t5_prod_drop_2
- model=20B
- model.positional_embedding=alibi
- deepspeed_path=config/deepspeed/bf16_zero2d_shard16.json
- trainer.precision=bf16 
- trainer.limit_val_batches=25
- trainer.val_check_interval=2000
- callback.save_every_n_train_steps=2000
- trainer.num_sanity_val_steps=0
- ++model.load_method=safe_state_dict 
- ++model.state_dict_path=/mnt_out/colehawk/easel/20b_ckpt/model_fp32_state_dict 
- optimizer.lr_scheduler_type=hotfix_inverse_square_root
- optimizer.micro_batch_size=2
- optimizer.total_batch_size=3040
- trainer.num_nodes=190
- ++data.autotokenizer_path=/mnt/colehawk/bedrock_prod_automodels/tokenizer/
command:
- /usr/bin/python3
image: 747303060528.dkr.ecr.us-east-1.amazonaws.com/mstar-eks:colehawk-bedrock_new
name: chawk-bdrk-20B-p4
node_num: 190
node_type: p4d.24xlarge
