default:
  image: nvidia/cuda:11.5.0-devel-ubuntu20.04

stages:
  - test
  - docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pytest:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install torch==1.11.0+cu115 -f https://download.pytorch.org/whl/cu115/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - python3 -m pytest ./tests --ignore=./tests/test_multi_gpu

pytest-multi-gpu:
  stage: test
  tags:
    - multi-gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install torch==1.11.0+cu115 -f https://download.pytorch.org/whl/cu115/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - python3 -m pytest ./tests/test_multi_gpu

lint:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install --upgrade prospector pip
    - python3 -m pip install torch==1.11.0+cu115 -f https://download.pytorch.org/whl/cu115/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons pickle5 --no-build-isolation
    - prospector src/

build_push_image:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - gpu
  script:
    - export AWS_SDK_LOAD_CONFIG=true
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/tools/docker/Dockerfile"
      --destination "747303060528.dkr.ecr.us-east-2.amazonaws.com/mstar-gitlab:$CI_COMMIT_REF_NAME"
      --cache=true
