default:
  image: nvidia/cuda:11.3.1-devel-ubuntu20.04

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pytest:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - python3 -m pytest ./tests

lint:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install --upgrade prospector pip
    - python3 -m pip install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons pickle5 --no-build-isolation
    - prospector src/
