default:
  image: python:3.8-buster

stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pytest:
  stage: test
  script:
    - python3 -m pip install pytest
    - python3 -m pip install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - python3 -m pytest ./tests

lint:
  stage: test
  script:
    - python3 -m pip install prospector
    - python3 -m pip install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - python3 -m pip install -e .  --no-build-isolation
    - python3 -m pip install --upgrade enscons pickle5 --no-build-isolation
    - prospector src/
