default:
  image: nvidia/cuda:11.6.1-devel-ubuntu20.04

stages:
  - test
  - docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pytest-py37:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt install software-properties-common -y
    - DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:deadsnakes/ppa
    - apt-get install -y python3-pip git ninja-build
    - apt-get install -y python3.7 python3.7-distutils python3.7-dev
    - python3.7 -m pip install torch==1.12.0+cu116 -f https://download.pytorch.org/whl/cu116/torch_stable.html
    - python3.7 -m pip install -e '.[test]'  --no-build-isolation
    - python3.7 -m pip install --upgrade enscons --no-build-isolation
    - python3.7 -m pytest ./tests --ignore=./tests/test_multi_gpu

pytest:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install torch==1.12.0+cu116 -f https://download.pytorch.org/whl/cu116/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - python3 -m pytest ./tests --ignore=./tests/test_multi_gpu

pytest-multi-gpu:
  stage: test
  tags:
    - multi-gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install torch==1.12.0+cu116 -f https://download.pytorch.org/whl/cu116/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - python3 -m pytest ./tests/test_multi_gpu

pytest-bedrock-encoder-decoder:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install torch==1.12.0+cu116 -f https://download.pytorch.org/whl/cu116/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test,bedrock_encoder_decoder]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons --no-build-isolation
    - cd ./scripts/bedrock_encoder_decoder/src; python3 -m pytest ./tests/

lint:
  stage: test
  tags:
    - gpu
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip git ninja-build
    - python3 -m pip install --upgrade prospector pip
    - python3 -m pip install torch==1.12.0+cu116 -f https://download.pytorch.org/whl/cu116/torch_stable.html
    - FORCE_CUDA=1 python3 -m pip install -e '.[test]'  --no-build-isolation
    - python3 -m pip install --upgrade enscons pickle5 --no-build-isolation
    - prospector src/

build_push_image:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - gpu
  script:
    - export AWS_SDK_LOAD_CONFIG=true
    - export NEW_CI_COMMIT_REF_NAME="$(echo $CI_COMMIT_REF_NAME | sed -r 's/\//_/g')"
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/tools/docker/Dockerfile"
      --destination "747303060528.dkr.ecr.us-east-2.amazonaws.com/mstar-gitlab:$NEW_CI_COMMIT_REF_NAME"
      --cache=true
