defaults:
  - _self_
  - datamodule: tldr.yaml
  - model: sftp_t5large.yaml
  - training: cnndm.yaml

train_mode: True

EKSArgs:
  experiment_name: "kaixianl-RLFH"
  run_name: "v2-sftp-t5large-tldr"

hydra:
  run:
    dir: /hdd1/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# T5 large, T5 3B,11B SFT and SFTP exps. fine-tune on tldr, zero-shot transfer to cnn/dm