defaults:
  - _self_
  - datamodule: cnndm.yaml
  - model: cnndm.yaml
  - training: cnndm.yaml

train_mode: True

EKSArgs:
  experiment_name: "kaixianl-RLFH"
  run_name: "v1-t5-small-cnndm"

hydra:
  run:
    dir: /hdd1/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# This config reproduces exps supervised fine-tuning T5-small model on CNNDM dataset.