args:
- pretrain_main.py
- run_name=stage_2_1_9B_t5
- optimizer.base_learning_rate=0.00025
- trainer.num_nodes=16
- optimizer.micro_batch_size=4
- optimizer.total_batch_size=512
- model.positional_embedding=alibi
- deepspeed_path=config/deepspeed/bf16_stage2.json
- trainer.limit_val_batches=100
- trainer.precision=bf16 
- trainer.num_sanity_val_steps=2
- data=stage_2_t5
- trainer.max_steps=100000
- optimizer.lr_scheduler_type=linear 
- ++model.load_method=automodel
- ++model.automodel_path=/mnt/colehawk/bedrock_prod_automodels/stage_1/1_9B/ 
- ++data.autotokenizer_path=/mnt/colehawk/bedrock_prod_automodels/tokenizer
- model.ckpt_path=null
command:
- /usr/bin/python3
image: 747303060528.dkr.ecr.us-east-1.amazonaws.com/mstar-eks:colehawk-bedrock
name: chawk-bdrk-1-9B-stage2-t5
node_num: 16
node_type: p4d.24xlarge
