batch_size: 4
max_seq_len: 512 
summary_max_seq_len: 128
num_beams: 4
repetition_penalty: 1.2
length_penalty: 0.6
early_stopping: True
num_workers: 0
test_batch_size: 32
test_distributed_mode: False # set this as true during training for distributed evaluation.
generated_summary_path: "/hdd1/data/legal_summarization/generated_summaries/generated_128_512.json"
test_data_path: "/hdd1/data/legal_summarization/all_128_512.json"
datamodule_class: scripts.rlfh.datamodule.data_legal.InferenceDataModule
post_key: "original_text"
summary_key: "reference_summary"
uid_key: 'uid'