defaults:
    - _self_
    - trainer: base
    - optimizer: base
    - data: stage_1_consolidated_11_07
    - model: tiny
    - tokenizer: base
    - lightning: base

run_name: tmp 
experiment_name: tmp
deepspeed_path: config/deepspeed/bf16_zero2d.json
validate_only: 0 #skip all training, validate from checkpoint
