defaults:
    - _self_
    - trainer: base
    - optimizer: base
    - data: t5_prod
    - model: base
    - callback: base

run_name: 1_9B
experiment_name: easel-pretraining
deepspeed_path: config/deepspeed/stage2.json #can use zero2d if multimodel required
validate_only: 0 #skip all training
