args:
- --nnodes=16
- --nproc_per_node=8
- --max_restarts=0
- pretrain_main.py
- run_name=1_9B_stg1_no_kong_data_ablation
- max_steps=60000 #chosen for ~3 days
- model=1_9B
- experiment_name=colehawk/kong_data_ablation
- lightning/plugins/environment=torch_elastic #necessary for elastic controller
- model.ckpt_path="auto"
- optimization.optimizer.lr=0.0005
- optimization/scheduler=linear
- lightning.callbacks.checkpoint.every_n_train_steps=10000
- trainer.limit_val_batches=50
- optimization.micro_batch_size=4
- data=stage_2_01_06 #default is mixed
- data.collator_output_targets=t5 #override with t5 loss for stg1
- data.clm_max_doc=2 #only matters with mixed clm/t5 output
command: ["python3","-m","torch.distributed.run"]
image: 747303060528.dkr.ecr.us-east-1.amazonaws.com/mstar-eks:colehawk-bedrock-01-07-dev
name: colehawk-2b-nokong-stg1
node_type: p4d.24xlarge
dag_type: "elastic_job_dag" # elastic job dag type
node_num: 16
min_replica: 16
max_replica: 16
updated_replica: 16
max_dag_triggers: 16 # this parameter will trigger the restart of the dag if the launch job failed for some reason
env:
  HYDRA_FULL_ERROR: "1" #useful for cloudwatch debugging
