num_nodes: 1
check_val_every_n_epoch: 1
default_root_dir: /mnt_out/colehawk/easel/
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
gpus: -1
gradient_clip_val: 1.0
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
log_gpu_memory: null
max_epochs: null
max_steps: 100000
num_sanity_val_steps: 2
precision: 16
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: false 
resume_from_checkpoint: null
track_grad_norm: -1
val_check_interval: 5000
