args:
- pretrain_main.py
- run_name=2B_newlines_fix
- trainer.max_steps=100000
- optimization.micro_batch_size=4
- optimization/scheduler=linear
- optimization.optimizer.lr=0.00005
- trainer.limit_val_batches=50
- tokenizer.pretrained_model_name_or_path=/mnt/tokenizer/mstar-t5-20B-bedrock-stage_2_t5_600B_embed_fix-nfkc
- model=1_9B
- data=stage_2_11_29_22
- model.state_dict_path=/mnt/colehawk/bedrock/nfkc_fix/2B/pytorch_model.bin
- lightning.callbacks.checkpoint.every_n_train_steps=10000 
command:
- /usr/bin/python3
image: 747303060528.dkr.ecr.us-east-2.amazonaws.com/mstar-eks:colehawk-newlines-01-03
name: colehawk-2B
node_num: 16 #can be any number due to shard8
node_type: p4d.24xlarge
