args:
- pretrain_main.py
- run_name=bart_100B_high_mask
- trainer.max_steps=500000
- trainer.num_nodes=8
- optimizer.micro_batch_size=8
- optimizer.total_batch_size=512
- optimizer.base_learning_rate=0.0001
- data=bart_25 #use bart collator
command:
- /usr/bin/python3
gpu: 8
image: 747303060528.dkr.ecr.us-east-1.amazonaws.com/mstar-eks:colehawk-easel
name: chawk-bart-high-mask-100B
node_num: 8
node_type: p4d.24xlarge
