name: "chawk-esl-gelu-test-lr"
node_type: "p4d.24xlarge"
node_num: 
gpu: 8
image: 747303060528.dkr.ecr.REGION_TAG.amazonaws.com/mstar-eks:USER_TAG-NAME_TAG
command: ["/usr/bin/python3"]
args: [
    "pretrain_main.py",
    "run_name=test_gelu_lr_5e-4",
    "model.config_path=config/model/gelu_1_9B.json",
    "optimizer.base_learning_rate=0.0005",
    "optimizer.base_max_steps=10000",
    "trainer.max_steps=10000"
]
