seed: null
trainer:
  logger: true
  checkpoint_callback: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 8
  auto_select_gpus: false
  tpu_cores: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 4
  max_epochs: null
  min_epochs: null
  max_steps: 250000
  min_steps: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: false
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: ddp_sharded
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  bert_cfg:
    vocab_size: 30522
    units: 768
    hidden_size: 3072
    max_length: 512
    num_heads: 12
    num_layers: 12
    pos_embed_type: learned
    activation: gelu
    pre_norm: false
    layer_norm_eps: 1.0e-12
    num_token_types: 2
    hidden_dropout_prob: 0.1
    attention_dropout_prob: 0.1
    dtype: float32
    layout: NT
    compute_layout: auto
  optimizer_cfg:
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.95
    learning_rate: 0.0003
    warmup_ratio: 0.01
    phase2: true
    phase1_num_steps: 225000
  ner_cfg:
    vocab_size: 81
data:
  qt_dir: test_qt
  ner_dir: ner_feather
  distributedsampler_seed: 0
  batch_size: 8
  num_workers: 4
  mmap_folder: /dev/shm/mstar
