args:
- pretrain_main.py
- run_name=reddit_100B_t5
- trainer.max_steps=100000
- optimizer.base_learning_rate=0.0001
- trainer.num_nodes=8
- optimizer.micro_batch_size=8
- optimizer.total_batch_size=512
- data=t5_reddit
command:
- /usr/bin/python3
gpu: 8
image: 747303060528.dkr.ecr.us-east-1.amazonaws.com/mstar-eks:colehawk-easel
name: chawk-bdrk-reddit-t5
node_num: 8
node_type: p4d.24xlarge
